name: rx
version: 0.0.1

author: Lukas Renggli <renggli@gmail.com>
homepage: https://github.com/renggli/dart-rx
description: Reactive Extensions Library for Dart providing an API for asynchronous programming with observable streams.

environment:
  sdk: '>=2.4.0 <3.0.0'
dependencies:
  collection: ^1.14.0
  meta: ^1.1.0
  more: ^1.18.0
dev_dependencies:
  test: ^1.6.0